---
- name: Creación de la base de datos Postgres
  community.postgresql.postgresql_db:
    name: "{{db_name}}"
  become: yes
  become_user: postgres
  
- name: Creación del usuario
  community.postgresql.postgresql_user:
    login_db: "{{db_name}}"
    name: "{{db_user}}"
    password: "{{db_passwd}}"
  become: yes
  become_user: postgres
  
- name: Concesión de permisos al usuario
  community.postgresql.postgresql_privs:
    database: "{{db_name}}"
    privs: CREATE
    type: schema
    objs: public
    roles: "{{db_user}}"
  become: yes
  become_user: postgres
